### ISSUE TITLE
Re-implement incidence compartments

### ISSUE THREAD

**Issue by eho-tacc** [eho-tacc/episimlab#37]
Re-implement reporting of incidence compartments. Formatted like `<compt>2<compt>` , e.g. `Iy2Ih`. Currently, can only track the *net* incident change in a compartment's state, which includes in and out edges applied during that time step. The ask is to expose the *contribution* of connected compartments to a given compartment at each time step. In the case of `Iy2Ih`: how many people went from `Iy` to `Ih` at this timestep, which is not the same as "how much did `Ih` change?

These incidence compartments are still calculated in SEIR functions for Cython:

https://github.com/eho-tacc/episimlab/blob/9e639575e5c8810b1d811d381944dfed557b9f2b/episimlab/seir/bf_cython_engine.pyx#L592-L592

and for plain Python:

https://github.com/eho-tacc/episimlab/blob/9e639575e5c8810b1d811d381944dfed557b9f2b/episimlab/seir/brute_force.py#L228-L228

They are also still included in the default compartment coordinates:

https://github.com/eho-tacc/episimlab/blob/9e639575e5c8810b1d811d381944dfed557b9f2b/episimlab/setup/coords.py#L22-L22

...but are expected by this test to be NaNs as implemented currently on the `27-housekeeping` branch:

https://github.com/eho-tacc/episimlab/blob/0f33f2dd25f448b490d79db9db370b2649c03e6c/tests/test_seir/test_bf_cython_seir.py#L31-L34

**Comment by kellypierce** [comment]
resolved in https://github.com/eho-tacc/episimlab/pull/38
